name: Publish Plugin to Portal

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: macos-latest
    env:
      GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
      GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - id: get_version
        uses: battila7/get-version-action@v2.2.1

      - name: Set version
        run: echo "RELEASE_VERSION="${{ steps.get_version.outputs.version-without-v }} >> $GITHUB_ENV

      - name: Cache Gradle Caches
        uses: gradle/gradle-build-action@v3

      - name: Run Gradle tasks
        run: ./gradlew preMerge --continue

      - name: Publish on Plugin Portal
        run: ./gradlew --project-dir plugin-build setupPluginUploadFromEnvironment publishPlugins
        if: success()
